name: Deploy React app

on: 
push:
  branches:
    - main

permissions:
  content: read
  pages: write
  id-toke: write
  
jobs:
  build:
    runs-on: ubunto-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1